name: channel_store
description: A simple and flexible state management library for flutter.
version: 1.1.1
homepage: https://github.com/oh-jinsu/channel_store

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: